### ISSUE TITLE
printing the . 

### ISSUE THREAD

**Issue by vnijs** [gluc/data.tree#84] opened 2016-10-01 20:08 UTC
On some machines when printing a tree the . is replaced by <U+00A6> <U+00B0>. See screenshot below. I haven't seen this on a mac but have on linux and windows. Any idea how to get the . to print appropriately?

<img width="666" alt="screen shot 2016-10-01 at 1 07 31 pm" src="https://cloud.githubusercontent.com/assets/2998956/19016751/1b227154-87d8-11e6-8c58-db5474b6f3e2.png">

**Comment by gluc** [comment] 2016-12-12 06:48
Hmm, that's a problem with the unicode characters. Tried on Windows and Ubuntu, but cannot reproduce :-(

**Comment by Elucidase** [comment] 2020-06-15 12:55
I had the same problem and I fixed it by setting locale:
```r
Sys.setlocale(category = "LC_CTYPE", locale = "English_United States.1252")
```

**Comment by gluc** [comment] 2020-06-15 13:00
Thx, @Elucidase , for this workaround. If anyone wants to have a go at fixing for good, pls be my guest. Closing this issue for now as valid workaround exists.

**Closed by gluc** 2020-06-15 13:00 UTC
Labels: bug
